[package]
name = "userinit"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib.workspace = true
linked_list_allocator.workspace = true
rbpf = { version = "0.3.0", default-features = false}

[lints]
workspace = true
